baseURL: "https://ds-r.leovan.tech/"
languageCode: "zh-cn"
title: "R 语言数据科学导论 | Data Science Introduction with R"
googleAnalytics: "G-MCPZ7NTLEX"
ignoreFiles: [
  "\\.Rmarkdown$", "\\.Rmd$", "\\.knit\\.md$", "\\.utf8\\.md$",
  "_files$", "_cache$", "\\.txt$", "\\.csv$", "\\.tsv$",
  "\\.tgz$", "\\.tar$", "\\.gz$", "\\.zip$", "\\.npz$"]
hasCJKLanguage: true
enableEmoji: true
rssLimit: 100

disableKinds: ["taxonomy", "term"]

permalinks:
  lecture: "/lecture/:slug/"
  doc: "/doc/:slug/"

menu:
  main:
    - name: "讲义"
      url: "/lecture/"
      weight: 1
    - name: "文档"
      url: "/doc/"
      weight: 2
    - name: "关于"
      url: "/about/"
      weight: 3

params:
  title: "R 语言数据科学导论"
  subtitle: "Data Science Introduction with R"
  author: "范叶亮"
  description: "R 语言数据科学导论 | Data Science Introduction with R"
  logo: "/images/data-science-introduction-with-r.png"
  logoWidth: 150
  footer: "Copyright &copy; 2017-{Year} [范叶亮](https://leovan.me)"
  licenseURL: "https://github.com/leovan/data-science-introduction-with-r/blob/main/LICENSE"
  googleAdsense: "ca-pub-2608165017777396"

  socialIcons:
    - title: "版本"
      icon: "https://img.shields.io/github/release/leovan/data-science-introduction-with-r.svg"
    - title: "许可证"
      icon: "https://img.shields.io/badge/license-CC%20BY--NC--SA%204.0-blue.svg"
    - title: "Github Stars"
      icon: "https://img.shields.io/github/stars/leovan/data-science-introduction-with-r?style=social"
      url: "https://github.com/leovan/data-science-introduction-with-r"
  buttons:
    - title: "讲义"
      url: "/lecture/"
    - title: "文档"
      url: "/doc/"
    - title: "关于"
      url: "/about/"

  clipboardjsVersion: "2.0.11"
  lazysizesVersion: "5.3.2"
  mathjaxVersion: "3.2.2"
  jsCookieVersion: "3.0.5"
  pdfjsVersion: "4.0.379"
  prismjsVersion: "1.29.0"
  vanillaBackToTopVersion: "latest"

markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
    parser:
      autoHeadingIDType: blackfriday
  tableOfContents:
    startLevel: 1
